### ISSUE TITLE
Metadata causing crash

### ISSUE THREAD

**Issue by prettyinpossible** [melike2d/itunes-presence#2]
When an album title is simply just a number, it crashes the application

for example: the album "7" by David Guetta

**Comment by viztea** [comment]
Thanks for creating an issue! I've fixed this locally and I'll be creating a release in a couple of minutes.

**Comment by viztea** [comment]
Just released https://github.com/melike2d/itunes-presence/releases/tag/1.1, lmk if this fixes your issue.

**Comment by prettyinpossible** [comment]
> 

It's fixed! Thank you for your work <3
