### ISSUE TITLE
Accented characters show as "�"

### ISSUE THREAD

**Issue by prettyinpossible** [melike2d/itunes-presence#3]
All accented characters display on the presence as "�"

For example, any of these (although I'm certain there's more): àèìòùÀÈÌÒÙáéíóúýÁÉÍÓÚÝâêîôûÂÊÎÔÛãñõÃÑÕäëïöüÿÄËÏÖÜŸåÅæÆœŒçÇðÐøØß

This results in the album artwork not displaying either:
![image](https://user-images.githubusercontent.com/122236329/211518390-d22041c0-1b8d-4953-ad1f-fd778d28814e.png)

**Comment by viztea** [comment]
Weird... I may know why though, could you comment the link to that track?

**Comment by prettyinpossible** [comment]
> Weird... I may know why though, could you comment the link to that track?

https://music.apple.com/gb/album/pl4yg1rl/1644398814?i=1644398816

**Comment by viztea** [comment]
Yup. My bad, it was a regression in the latest release. I'll create a new one in a couple of minutes.

Good song btw

**Comment by prettyinpossible** [comment]
> Yup. My bad, it was a regression in the latest release. I'll create a new one in a couple of minutes.

Sickkkk thank you :-)

> Good song btw

I know right!

**Comment by viztea** [comment]
https://github.com/melike2d/itunes-presence/releases/tag/1.1.1 just released. Thanks for the bug report! :D
