### ISSUE TITLE
Wrong album artwork

### ISSUE THREAD

**Issue by prettyinpossible** [melike2d/itunes-presence#4]
Not sure what causes it but sometimes the wrong album artwork gets pulled

![image](https://user-images.githubusercontent.com/122236329/220724712-cd3c098a-241a-4110-a8e5-4825cc888c09.png)

**Comment by viztea** [comment]
Since iTunes doesn't expose any apple music information to us through the scripting interface, I need to manually search Apple Music for matching tracks. 

I did do some experimenting but couldn't find any solution :/
